[[order]]

[[order.group]]
id = "heroku/python"
optional = true
version = "0.4.0"

[[order.group]]
id = "heroku/jvm"
version = "0.1.0"

[[order.group]]
id = "jkutner/minecraft-server"
version = "0.1.1"
